Improve Locale Support
Previously, the devbox user would default to the `POSIX` locale
which meant that a lot of minor things around UTF-8 would not
work.

We now update the locale to use one with UTF-8 support; note that
we just use the minimal C locale instead of building one. Users
can (if they chose) use something like `dpkg-reconfigure locales`
and `update-locale` in order to modify their default locale if
they want something else specific.

Additionally, get rid of the annoying known hosts warning, by
keeping a devbox specific known hosts file.

diff --git a/dbx-proxy b/dbx-proxy
--- a/dbx-proxy
+++ b/dbx-proxy
@@ -1,11 +1,17 @@
 #!/usr/bin/env bash
 # SPDX-License-Identifier: GPL-3.0-only
-# SPDX-FileCopyrightText: 2026 Nicholas Rodrigues Lordello <n@lordello.net>
 
 set -euo pipefail
 
+if [[ $# -ne 1 ]]; then
+	echo "ERROR: missing port to proxy" >&2
+	exit 1
+fi
+
 root="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
 machine="${DBX_MACHINE:-dbx}"
+port="$1"
 
 "$root/dbx-start"
-exec ssh "$machine" -F "$root/ssh/$machine.config"
+exec ssh "$machine" -F "$root/ssh/$machine.config" \
+	-L "localhost:$port:localhost:$port" -N
