Quieter Output

diff --git a/dbx-init b/dbx-init
--- a/dbx-init
+++ b/dbx-init
@@ -4,7 +4,8 @@
 set -euo pipefail
 
 if [[ ! -f /run/.dbxenv ]]; then
-    echo "ERROR: not in a devbox" >&2
+	echo "ERROR: not in a devbox" >&2
+	exit 1
 fi
 
 exec tini /usr/sbin/sshd -- -D -e
