Started Adapting for Apple Containers

diff --git a/dbx-create b/dbx-create
--- a/dbx-create
+++ b/dbx-create
@@ -3,23 +3,42 @@
 
 set -euo pipefail
 
-r="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
-c="dbx"
-d="$HOME/Developer"
+R="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
+C="dbx"
 
-if podman container exists "$c"; then
-    echo "already created"
-    exit
-fi
+echo "TODO:"
+echo "- create temporary SSH key"
+echo "- generate SSH configuration for host and guest"
+echo "- create base container image"
+echo "  - initialize user"
+echo "  - add authorized keys for SSH login"
+echo "  - install required packages (sshd and tini)"
+echo "  - install nice to have packages (see toolbox image)"
+echo "  - setup socket cleanup with sshd_config"
+echo "- magic encantation to create container"
 
-podman create \
-    --hostname dbx \
-    --label manager=dbx \
-    --name "$c" \
-    --user root:root \
-    --userns keep-id \
-    --volume "$d:$d:z" \
-    --volume "$r/dbx-init:/usr/local/bin/dbx-init:ro,z" \
-    registry.fedoraproject.org/fedora-toolbox:43 \
-    dbx-init "$(id -u)" "$(id -g)"
-podman start "$c" >/dev/null
+#if ! id $DBX_USER &>/dev/null; then
+#	useradd \
+#		--comment "$DBX_USER_COMMENT" \
+#		--create-home \
+#		--groups sudo \
+#		--shell /usr/bin/bash \
+#		--uid 1000 \
+#		--user-group \
+#		$DBX_USER
+#fi
+# if container list --all | grep $C >/dev/null; then
+# 	echo "already created"
+# 	exit
+# fi
+# podman create \
+# 	--hostname dbx \
+# 	--label manager=dbx \
+# 	--name "$c" \
+# 	--user root:root \
+# 	--userns keep-id \
+# 	--volume "$d:$d:z" \
+# 	--volume "$r/dbx-init:/usr/local/bin/dbx-init:ro,z" \
+# 	registry.fedoraproject.org/fedora-toolbox:43 \
+# 	dbx-init "$(id -u)" "$(id -g)"
+# podman start "$c" >/dev/null
diff --git a/dbx-init b/dbx-init
--- a/dbx-init
+++ b/dbx-init
@@ -3,34 +3,8 @@
 
 set -euo pipefail
 
-if [[ ! -f /run/.containerenv ]]; then
-    echo "ERROR: not in a container" >&2
+if [[ ! -f /run/.dbxenv ]]; then
+    echo "ERROR: not in a devbox" >&2
 fi
 
-h="/dbx"
-u="${1:-1000}"
-g="${2:-1000}"
-
-dnf install -y \
-    fish \
-    fzf \
-    netcat \
-    ripgrep \
-    tini \
-    vim-enhanced
-
-if [[ ! -d "$h" ]]; then
-    usermod \
-        --home "$h" \
-        --groups wheel \
-        --password "" \
-        --shell $(command -v fish) \
-        $(id -nu "$u")
-
-    mkdir --parents "$h"
-    chown --recursive "$u:$g" "$h"
-fi
-
-echo "=== READY TO ROLL! ==="
-touch /run/.dbxenv
-exec tini sleep -- infinity
+exec tini sshd -- -D -e
